# Generated by Django 4.2.4 on 2023-09-19 19:50

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='название')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='URL')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Заголовок',
                'verbose_name_plural': 'заголовки',
            },
        ),
        migrations.CreateModel(
            name='Lib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='название')),
                ('site', models.CharField(max_length=120, null=True, verbose_name='Официальный сайт')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Библиотека',
                'verbose_name_plural': 'библиотеки',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_libs.directory', verbose_name='Родительский заголовок')),
            ],
            options={
                'verbose_name': 'Подзаголовок',
                'verbose_name_plural': 'подзаголовки',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_libs.topic', verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'записи',
            },
        ),
        migrations.AddField(
            model_name='directory',
            name='lib',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='all_libs.lib', verbose_name='библиотека'),
        ),
        migrations.AddField(
            model_name='directory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='all_libs.directory', verbose_name='родительский заголовок'),
        ),
    ]
