# Generated by Django 4.2.4 on 2023-09-28 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_libs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='lib',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_libs.lib', verbose_name='библиотека'),
        ),
    ]
