# Generated by Django 4.2.4 on 2023-10-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_libs', '0002_alter_directory_lib'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=models.SlugField(default='sss', max_length=256, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='sss', max_length=256, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
