# Generated by Django 4.2.4 on 2023-11-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_libs', '0003_entry_slug_topic_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Библиотека',
                'verbose_name_plural': 'библиотеки',
            },
        ),
        migrations.AlterField(
            model_name='lib',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
