# Generated by Django 4.2.4 on 2023-11-04 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_libs', '0004_chapter_alter_lib_name_alter_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lib',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='all_libs.chapter', verbose_name='раздел'),
            preserve_default=False,
        ),
    ]
