# Generated by Django 4.2.4 on 2024-02-07 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_libs', '0005_lib_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('about', models.TextField()),
                ('lib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_libs.lib')),
            ],
        ),
    ]
