# Generated by Django 4.2.4 on 2024-02-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_libs', '0006_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='class_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
