# Generated by Django 4.2.4 on 2024-02-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_libs', '0007_command_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='class_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
