# Generated by Django 4.2.4 on 2024-02-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_libs', '0008_alter_command_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lib',
            name='site',
            field=models.URLField(max_length=120, null=True, verbose_name='Официальный сайт'),
        ),
    ]
