# Generated by Django 4.2.4 on 2024-03-02 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_libs', '0009_alter_lib_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadEntryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='upload_images/%Y/%m/%d')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_libs.entry')),
            ],
        ),
    ]
