# Generated by Django 4.2.4 on 2024-03-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_libs', '0010_uploadentryphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadentryphoto',
            name='image',
            field=models.ImageField(default=None, upload_to='upload_images/%Y/%m/%d'),
        ),
    ]
