# Generated by Django 4.2.4 on 2024-03-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_libs', '0011_alter_uploadentryphoto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='class_name',
        ),
        migrations.AddField(
            model_name='command',
            name='slug',
            field=models.SlugField(default='_', max_length=256, unique=True),
        ),
    ]
