# Generated by Django 4.2.4 on 2024-03-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_libs', '0012_remove_command_class_name_command_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
    ]
