# Generated by Django 4.2.4 on 2024-04-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_libs', '0013_alter_command_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadentryphoto',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
